sonar.projectKey=rag-api
sonar.projectName=rag-api
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.host.url=http://sonar.local
sonar.python.version=3.10

sonar.exclusions=venv/**,__pycache__/**,.git/**,data/**,chroma/**,docker_data/**,docker_chroma/**,*.pdf,*.png,*.jpg,*.jpeg,*.zip,*.tar,*.gz,rag-ui/**
