sonar.projectKey=rag-api
sonar.projectName=rag-api
sonar.projectVersion=1.0

# Dossier source à analyser
sonar.sources=.

# Encodage
sonar.sourceEncoding=UTF-8

# Adresse SonarQube
sonar.host.url=http://sonar.local

# Token généré depuis SonarQube
sonar.token=sqp_40e9b078e24d76c28523bf43383100a28b937f7e

# Exclusions pour éviter d’analyser les fichiers inutiles ou lourds
sonar.exclusions=venv/**,__pycache__/**,.git/**,data/**,chroma/**,docker_data/**,docker_chroma/**,*.pdf,*.png,*.jpg,*.jpeg,*.zip,*.tar,*.gz

# Exclusions spécifiques Python
sonar.python.version=3.10
