apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      nodeSelector:
        role: api

      automountServiceAccountToken: false

      containers:
        - name: fastapi
          image: tech2026/rag-api:v25
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8000

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
              ephemeral-storage: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
              ephemeral-storage: "2Gi"

          env:
            - name: CHROMA_HOST
              value: "chromadb.chromadb.svc.cluster.local"

            - name: CHROMA_PORT
              value: "8000"

            - name: DATA_PATH
              value: "/app/data"

            - name: OLLAMA_BASE_URL
              value: "http://ollama.ollama.svc.cluster.local:11434"

            - name: OLLAMA_MODEL
              value: "mistral"

            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow.mlflow.svc.cluster.local:5000"

            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hf-secret
                  key: HF_TOKEN
